---
language: python
services:
  - docker
python:
  - "2.7"
  - "3.7"
env:
  - PIP_VERSION_NUMBER=3
  - PIP_VERSION_NUMBER=2
install:
  - pip install molecule
  - pip install docker
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
