---
language: python
services:
  - docker
python:
  - "2.7"
  - "3.6"
install:
  - pip install molecule
  - pip install docker
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
