---

- name: Determine pip version to install and use
  set_fact:
    pip_version_to_use: >-
      {%- if pip_version -%}
        {%- if pip_version|int == 3 -%}
          3
        {%- elif pip_version|int == 2 -%}
          2
        {%- endif -%}
      {%- elif ansible_python.version.major|int == 3 -%}
        3
      {%- elif ansible_python.version.major|int == 2 -%}
        2
      {%- endif -%}

- name: Set pip version to {{ pip_version_to_use }}
  set_fact:
    pip_apt_package: >-
      {%- if pip_version_to_use|int == 3 -%}
        python3-pip
      {%- elif pip_version_to_use|int == 2 -%}
        python-pip
      {%- endif -%}
    pip_executable: >-
      {%- if pip_version_to_use|int == 3 -%}
        pip3
      {%- elif pip_version_to_use|int == 2 -%}
        pip2
      {%- endif -%}

- name: Install pip{{ pip_version_to_use }}
  apt:
    name: "{{ pip_apt_package }}"
    state: present
  register: result
  until: result is success
  retries: 5
  delay: 5

- name: Check if setuptools is needed
  set_fact:
    pip_setuptools_package: >-
      {%- if pip_version_to_use|int != ansible_python.version.major|int -%}
        {%- if ansible_python.version.major == 3 -%}
          python3-setuptools
        {%- elif ansible_python.version.major == 2 -%}
          python-setuptools
        {%- endif -%}
      {%- else -%}
        []
      {%- endif -%}

- name: Install setuptools
  apt:
    name: "{{ pip_setuptools_package }}"
    state: present
  register: result
  until: result is success
  retries: 5
  delay: 5
  when: pip_setuptools_package | length

- name: Install pip package/s
  pip:
    name: "{{ (item.name | default(item)) if item.requirements is not defined else omit }}"
    version: "{{ item.version | default(omit) }}"
    requirements: "{{ item.requirements | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    virtualenv_command: "{{ item.virtualenv_command | default(omit) }}"
    virtualenv_python: "{{ item.virtualenv_python | default(omit) }}"
    virtualenv_site_packages: "{{ item.virtualenv_site_packages | default(omit) }}"
    extra_args: "{{ item.extra_args | default(omit) }}"
    umask: "{{ item.umask | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: >-
      {%- if item.virtualenv is defined -%}
        {{ omit }}
      {%- elif item.executable is defined -%}
        {{ item.executable }}
      {%- else -%}
        {{ pip_executable }}
      {%- endif -%}
  loop: "{{ pip_install_packages }}"
