---

- name: Install pip for Python version Ansible is using
  apt:
    name:
      "python{{ (3 if pip_version==3 else '') if pip_version else (3 if ansible_python.version.major==3 else '') }}-pip"
    state: present
  register: result
  until: result is success
  retries: 5
  delay: 5

- name: Install pip packages
  pip:
    name: "{{ (item.name | default(item)) if item.requirements is not defined else omit }}"
    version: "{{ item.version | default(omit) }}"
    requirements: "{{ item.requirements | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    virtualenv_command: "{{ item.virtualenv_command | default(omit) }}"
    virtualenv_python: "{{ item.virtualenv_python | default(omit) }}"
    virtualenv_site_packages: "{{ item.virtualenv_site_packages | default(omit) }}"
    extra_args: "{{ item.extra_args | default(omit) }}"
    umask: "{{ item.umask | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ omit if item.virtualenv is defined else ('pip3' if ansible_python.version.major == 3 else 'pip') }}"
  loop: "{{ pip_install_packages }}"
