---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ansible-pip
    image: ubuntu:${UBUNTU_IMAGE_TAG:-latest}
provisioner:
  name: ansible
  options:
    v: true
  lint:
    name: ansible-lint
  playbooks:
    converge: playbook.yml
    side_effect: side_effect.yml
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
