---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ansible-pip
    image: ubuntu:${UBUNTU_IMAGE_TAG:-latest}
provisioner:
  name: ansible
  inventory:
    host_vars:
      all:
        ansible_python_interpreter: /usr/bin/python${PYTHON_INTERPRETOR:-2}
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
